services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
    networks:
      - app-network

  client:
    build:
      context: ./src/client
    container_name: client
    ports:
      - "5001:5000"
    networks:
      - app-network

  server:
    build:
      context: ./src/server
    container_name: server
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - queue
    networks:
      - app-network

  queue:
    image: "rabbitmq:3-management"
    container_name: queue
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  test:
    build:
      context: ./src/server
    container_name: test
    command: npm test
    depends_on:
      - server
      - queue
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
